name: PyTest

on:
  workflow_dispatch

jobs:
  testsuite:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get credentials
        run: |
          echo "TAPIS_USER=${{ secrets.TAPIS_ACCOUNT }}" >> "$GITHUB_ENV"
          echo "TAPIS_PASSWORD=${{ secrets.TAPIS_PASSWORD }}" >> "$GITHUB_ENV"
          echo "HOST_USER=${{ secrets.HOST_USER }}" >> "$GITHUB_ENV"
          echo "HOST_IP_ADDR=${{ secrets.HOST_IP_ADDR }}" >> "$GITHUB_ENV"
          {
            echo "HOST_PKEY<<EOF"
            echo "${{ secrets.HOST_PKEY}}"
            echo "EOF"
          } >> "$GITHUB_ENV"
      - name: Run tests
        run: pytest --junit-xml=report.xml .
        continue-on-error: true
      - name: Convert to ctrf
        run: npx junit-to-ctrf ./report.xml -o ./report.json
      - name: Run CTRF annotations
        run: npx github-actions-ctrf ./report.json
        if: always()
      #- name: Upload report
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest_results
      #    path: results.html
