name: PyTest

on:
  workflow_dispatch:
    inputs:
      ct_version:
        description: 'Camera Traps release'
        required: true
        type: string
  repository_dispatch:
    types: [dispatch-event]

jobs:
  generate-matrix:
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.gen_matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies (only needed for the script)
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate experiment matrix
        id: gen_matrix
        run: |
          python3 .github/scripts/gen_matrix.py > matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  testsuite:
    needs: generate-matrix
    runs-on: self-hosted
    environment: main
    strategy:
      matrix:
        include: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Node.js
        uses: actions/setup-node@v7
      - name: Get credentials
        run: |
          if [[ ${{ github.event_name == 'workflow_dispatch' }} == true ]]; then
            echo "CT_VERSION=${{ inputs.ct_version }}" >> "$GITHUB_ENV"
          elif [[ ${{ github.event_name == 'repository_dispatch' }} == true ]]; then
            echo "CT_VERSION=${{ github.event.client_payload.ct_version }}" >> "$GITHUB_ENV"
          fi
          echo "TAPIS_USER=${{ secrets.TAPIS_ACCOUNT }}" >> "$GITHUB_ENV"
          echo "TAPIS_PASSWORD=${{ secrets.TAPIS_PASSWORD }}" >> "$GITHUB_ENV"
          echo "HOST_USER=${{ secrets.HOST_USER }}" >> "$GITHUB_ENV"
          echo "HOST_IP_ADDR=${{ secrets.HOST_IP_ADDR }}" >> "$GITHUB_ENV"
          {
            echo "HOST_PKEY<<EOF"
            echo "${{ secrets.HOST_PKEY}}"
            echo "EOF"
          } >> "$GITHUB_ENV"
      - name: Run ${{ matrix.full_id }}
        run: |
          python -m pytest -k "${{ matrix.k_id }}" --junit-xml=report.xml .
        continue-on-error: true
      - name: Convert to ctrf
        run: npx junit-to-ctrf ./report.xml -o ./report.json
      - name: Run CTRF annotations
        run: npx github-actions-ctrf ./report.json
        if: always()
      - name: Get test result
        if: always()
        run: python3 .github/scripts/get_test_result.py
        continue-on-error: false
