name: PyTest

on:
  workflow_dispatch

jobs:
  testsuite:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get credentials
        run: |
          echo "TAPIS_USER=${{ secrets.TAPIS_ACCOUNT }}" >> "$GITHUB_ENV"
          echo "TAPIS_PASSWORD=${{ secrets.TAPIS_PASSWORD }}" >> "$GITHUB_ENV"
      - name: Run tests
        run: pytest --html=results.html .
        continue-on-error: true
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: pytest_results.html
          path: results.html
